---
default_language_version: {python: python3}
minimum_pre_commit_version: "1.15"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-yaml
        name: Check for valid YAML syntax in repo
        description: https://github.com/pre-commit/pre-commit-hooks/blob/master/pre_commit_hooks/check_yaml.py
      - id: detect-private-key
        name: Check for existence of private key in repo
        description: https://github.com/pre-commit/pre-commit-hooks/blob/master/pre_commit_hooks/detect_private_key.py
      - id: trailing-whitespace
        name: Remove trailing whitespace in YAML,Python,Bash files
        description: https://github.com/pre-commit/pre-commit-hooks/blob/master/pre_commit_hooks/trailing_whitespace_fixer.py
        files: \.(py|sh|yaml|yml)$
        exclude: fractals/anovik/fractals.py
      - id: end-of-file-fixer
        name: Ensure EOF is consistently only a newline
        description: https://github.com/pre-commit/pre-commit-hooks/blob/master/pre_commit_hooks/end_of_file_fixer.py
        files: \.(py|sh|yaml|yml)$
      - id: mixed-line-ending
        name: Ensure line-ending is consistent
        description: https://github.com/pre-commit/pre-commit-hooks/blob/master/pre_commit_hooks/mixed_line_ending.py
        files: \.(py|sh|yaml|yml)$
      - id: check-executables-have-shebangs
        name: Checks that non-binary executables have a proper shebang
        description: https://github.com/pre-commit/pre-commit-hooks/blob/master/pre_commit_hooks/check_executables_have_shebangs.py
        files: \.(py|sh)$
      - id: check-shebang-scripts-are-executable
        name: Checks that scripts with shebangs are executable.
        description: https://github.com/pre-commit/pre-commit-hooks/blob/master/pre_commit_hooks/check_shebang_scripts_are_executable.py
        files: \.(py|sh)$
      - id: check-json
        name: Attempts to load all json files to verify syntax.
        description: https://github.com/pre-commit/pre-commit-hooks/blob/master/pre_commit_hooks/check_json.py
        files: \.(json)$
      - id: check-toml
        name: Attempts to load all toml files to verify syntax.
        description: https://github.com/pre-commit/pre-commit-hooks/blob/master/pre_commit_hooks/check_toml.py
        files: \.(toml)$
      - id: check-yaml
        name: Attempts to load all yaml files to verify syntax.
        description: https://github.com/pre-commit/pre-commit-hooks/blob/master/pre_commit_hooks/check_yaml.py
        files: \.(yaml)$

  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
        exclude: fractals/anovik/fractals.py

  - repo: https://github.com/klen/pylama
    rev: 8.3.8
    hooks:
      - id: pylama
        args: ['-i', 'C901,E203,E501,E722']
        exclude: fractals/anovik/fractals.py
