FROM ruby:2.7-alpine

LABEL maintainer="Michele Adduci <adduci.michele@gmail.com>"

VOLUME /site

EXPOSE 4000

WORKDIR /site

RUN apk update && \
    apk --update add \
    gcc \
    g++ \
    make \
    curl \
	git \
    bison \
    ca-certificates \
    tzdata \
    ruby-rdoc \
    ruby-irb \
    ruby-bundler \
    ruby-nokogiri \
    ruby-dev \
    glib-dev \
    zlib-dev \
    libc-dev && \
    echo 'gem: --no-document' > /etc/gemrc && \
    gem install github-pages --version 223 && \
    gem install jekyll-watch jekyll-admin bigdecimal webrick && \
    apk del gcc g++ binutils bison git perl nodejs make curl && \
    rm -rf /var/cache/apk/*

ENTRYPOINT ["jekyll"]

